export const TreasuryAbi = [
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        }
     ],
     "name":"AssetAdded",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        }
     ],
     "name":"AssetRemoved",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"bool",
           "name":"_isSupported",
           "type":"bool"
        },
        {
           "indexed":false,
           "internalType":"uint8",
           "name":"_decimals",
           "type":"uint8"
        },
        {
           "indexed":false,
           "internalType":"uint16",
           "name":"_allocatedPercentage",
           "type":"uint16"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"_price",
           "type":"uint256"
        }
     ],
     "name":"AssetUpdated",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        
     ],
     "name":"CapitalPaused",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        
     ],
     "name":"CapitalUnpaused",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"uint8",
           "name":"version",
           "type":"uint8"
        }
     ],
     "name":"Initialized",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"_addr",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"_value",
           "type":"uint256"
        }
     ],
     "name":"Mint",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        }
     ],
     "name":"MintAssetAdded",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        }
     ],
     "name":"MintAssetRemoved",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        
     ],
     "name":"RebasePaused",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        
     ],
     "name":"RebaseUnpaused",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":false,
           "internalType":"address",
           "name":"_addr",
           "type":"address"
        },
        {
           "indexed":false,
           "internalType":"uint256",
           "name":"_value",
           "type":"uint256"
        }
     ],
     "name":"Redeem",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"bytes32",
           "name":"role",
           "type":"bytes32"
        },
        {
           "indexed":true,
           "internalType":"bytes32",
           "name":"previousAdminRole",
           "type":"bytes32"
        },
        {
           "indexed":true,
           "internalType":"bytes32",
           "name":"newAdminRole",
           "type":"bytes32"
        }
     ],
     "name":"RoleAdminChanged",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"bytes32",
           "name":"role",
           "type":"bytes32"
        },
        {
           "indexed":true,
           "internalType":"address",
           "name":"account",
           "type":"address"
        },
        {
           "indexed":true,
           "internalType":"address",
           "name":"sender",
           "type":"address"
        }
     ],
     "name":"RoleGranted",
     "type":"event"
  },
  {
     "anonymous":false,
     "inputs":[
        {
           "indexed":true,
           "internalType":"bytes32",
           "name":"role",
           "type":"bytes32"
        },
        {
           "indexed":true,
           "internalType":"address",
           "name":"account",
           "type":"address"
        },
        {
           "indexed":true,
           "internalType":"address",
           "name":"sender",
           "type":"address"
        }
     ],
     "name":"RoleRevoked",
     "type":"event"
  },
  {
     "stateMutability":"nonpayable",
     "type":"fallback"
  },
  {
     "inputs":[
        
     ],
     "name":"DEFAULT_ADMIN_ROLE",
     "outputs":[
        {
           "internalType":"bytes32",
           "name":"",
           "type":"bytes32"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"IMPLEMENTATION_SLOT",
     "outputs":[
        {
           "internalType":"bytes32",
           "name":"",
           "type":"bytes32"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"_dryp",
     "outputs":[
        {
           "internalType":"contract Dryp",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"_drypPoolPositionManager",
     "outputs":[
        {
           "internalType":"contract IPancakeswapV2PositionManager",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"inAmount",
           "type":"uint256"
        },
        {
           "internalType":"address",
           "name":"from",
           "type":"address"
        }
     ],
     "name":"_getDrypDollar",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"outAmount",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"_decimalin",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"_decimalOut",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"_amount",
           "type":"uint256"
        }
     ],
     "name":"_toUnitsPrice",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"pure",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"_treasury_manager",
     "outputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"_usdt",
     "outputs":[
        {
           "internalType":"address",
           "name":"",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        },
        {
           "internalType":"uint8",
           "name":"_decimals",
           "type":"uint8"
        },
        {
           "internalType":"uint16",
           "name":"_allocatedPercentage",
           "type":"uint16"
        },
        {
           "internalType":"uint32",
           "name":"_price",
           "type":"uint32"
        },
        {
           "internalType":"uint256",
           "name":"_amount",
           "type":"uint256"
        }
     ],
     "name":"addAsset",
     "outputs":[
        
     ],
     "stateMutability":"payable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        },
        {
           "internalType":"string",
           "name":"_symbol",
           "type":"string"
        },
        {
           "internalType":"uint8",
           "name":"_decimals",
           "type":"uint8"
        },
        {
           "internalType":"uint32",
           "name":"_price",
           "type":"uint32"
        }
     ],
     "name":"addMintingToken",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"_amount",
           "type":"uint256"
        }
     ],
     "name":"calculateRedeemOutputs",
     "outputs":[
        {
           "internalType":"uint256[]",
           "name":"",
           "type":"uint256[]"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"capitalPaused",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        }
     ],
     "name":"checkBalance",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"_amount",
           "type":"uint256"
        }
     ],
     "name":"depositToRedeemableBasket",
     "outputs":[
        
     ],
     "stateMutability":"payable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"_amount",
           "type":"uint256"
        }
     ],
     "name":"depositToUnRedeemableBasket",
     "outputs":[
        
     ],
     "stateMutability":"payable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"getAllAssets",
     "outputs":[
        {
           "internalType":"address[]",
           "name":"",
           "type":"address[]"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"getAllMinitingAssets",
     "outputs":[
        {
           "internalType":"address[]",
           "name":"",
           "type":"address[]"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"getImplementation",
     "outputs":[
        {
           "internalType":"address",
           "name":"impl",
           "type":"address"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        }
     ],
     "name":"getRedeemAssetConfig",
     "outputs":[
        {
           "components":[
              {
                 "internalType":"bool",
                 "name":"isSupported",
                 "type":"bool"
              },
              {
                 "internalType":"uint8",
                 "name":"decimals",
                 "type":"uint8"
              },
              {
                 "internalType":"uint16",
                 "name":"allotatedPercentange",
                 "type":"uint16"
              },
              {
                 "internalType":"uint256",
                 "name":"priceInUsdt",
                 "type":"uint256"
              },
              {
                 "internalType":"uint256",
                 "name":"amount",
                 "type":"uint256"
              }
           ],
           "internalType":"struct TreasuryStorage.TreasuryAsset",
           "name":"config",
           "type":"tuple"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"bytes32",
           "name":"role",
           "type":"bytes32"
        }
     ],
     "name":"getRoleAdmin",
     "outputs":[
        {
           "internalType":"bytes32",
           "name":"",
           "type":"bytes32"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        }
     ],
     "name":"getUnRedeemAssetConfig",
     "outputs":[
        {
           "components":[
              {
                 "internalType":"bool",
                 "name":"isSupported",
                 "type":"bool"
              },
              {
                 "internalType":"uint8",
                 "name":"decimals",
                 "type":"uint8"
              },
              {
                 "internalType":"uint16",
                 "name":"allotatedPercentange",
                 "type":"uint16"
              },
              {
                 "internalType":"uint256",
                 "name":"priceInUsdt",
                 "type":"uint256"
              },
              {
                 "internalType":"uint256",
                 "name":"amount",
                 "type":"uint256"
              }
           ],
           "internalType":"struct TreasuryStorage.TreasuryAsset",
           "name":"config",
           "type":"tuple"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"bytes32",
           "name":"role",
           "type":"bytes32"
        },
        {
           "internalType":"address",
           "name":"account",
           "type":"address"
        }
     ],
     "name":"grantRole",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"bytes32",
           "name":"role",
           "type":"bytes32"
        },
        {
           "internalType":"address",
           "name":"account",
           "type":"address"
        }
     ],
     "name":"hasRole",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"__drypToken",
           "type":"address"
        },
        {
           "internalType":"address",
           "name":"__drypPool",
           "type":"address"
        },
        {
           "internalType":"address",
           "name":"__treasuryManager",
           "type":"address"
        },
        {
           "internalType":"address",
           "name":"__usdt",
           "type":"address"
        }
     ],
     "name":"initialize",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"token",
           "type":"address"
        }
     ],
     "name":"isTokenAllowedForMiniting",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"isTreasuryStarted",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"_amount",
           "type":"uint256"
        },
        {
           "internalType":"uint256",
           "name":"_minimumDrypAmount",
           "type":"uint256"
        },
        {
           "internalType":"address",
           "name":"_recipient",
           "type":"address"
        }
     ],
     "name":"mint",
     "outputs":[
        
     ],
     "stateMutability":"payable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"pauseCapital",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"pauseRebase",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"rebasePaused",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"uint256",
           "name":"_amount",
           "type":"uint256"
        },
        {
           "internalType":"address",
           "name":"_recipient",
           "type":"address"
        }
     ],
     "name":"redeemAssets",
     "outputs":[
        
     ],
     "stateMutability":"payable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        }
     ],
     "name":"removeAsset",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        }
     ],
     "name":"removeMintingToken",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"bytes32",
           "name":"role",
           "type":"bytes32"
        },
        {
           "internalType":"address",
           "name":"account",
           "type":"address"
        }
     ],
     "name":"renounceRole",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"bytes32",
           "name":"role",
           "type":"bytes32"
        },
        {
           "internalType":"address",
           "name":"account",
           "type":"address"
        }
     ],
     "name":"revokeRole",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"newImpl",
           "type":"address"
        }
     ],
     "name":"setAdminImpl",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address[]",
           "name":"_assets",
           "type":"address[]"
        },
        {
           "internalType":"uint8[]",
           "name":"_decimals",
           "type":"uint8[]"
        },
        {
           "internalType":"uint16[]",
           "name":"_allocatPercentage",
           "type":"uint16[]"
        },
        {
           "internalType":"uint32[]",
           "name":"_price",
           "type":"uint32[]"
        },
        {
           "internalType":"uint256[]",
           "name":"_amounts",
           "type":"uint256[]"
        }
     ],
     "name":"startTreasury",
     "outputs":[
        
     ],
     "stateMutability":"payable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"bytes4",
           "name":"interfaceId",
           "type":"bytes4"
        }
     ],
     "name":"supportsInterface",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"totalValueLockedInNonRedeemBasket",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"totalValueLockedInRedeemBasket",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"totalValueLockedInRevenue",
     "outputs":[
        {
           "internalType":"uint256",
           "name":"",
           "type":"uint256"
        }
     ],
     "stateMutability":"view",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"unpauseCapital",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"unpauseRebase",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        },
        {
           "internalType":"bool",
           "name":"_isSupported",
           "type":"bool"
        },
        {
           "internalType":"uint8",
           "name":"_decimals",
           "type":"uint8"
        },
        {
           "internalType":"uint16",
           "name":"_allocatedPercentage",
           "type":"uint16"
        },
        {
           "internalType":"uint32",
           "name":"_price",
           "type":"uint32"
        }
     ],
     "name":"updateAssetToRedeemBasket",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        },
        {
           "internalType":"bool",
           "name":"_isSupported",
           "type":"bool"
        },
        {
           "internalType":"uint8",
           "name":"_decimals",
           "type":"uint8"
        },
        {
           "internalType":"uint16",
           "name":"_allocatedPercentage",
           "type":"uint16"
        },
        {
           "internalType":"uint32",
           "name":"_price",
           "type":"uint32"
        }
     ],
     "name":"updateAssetToUnRedeemBasket",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"newDrypAddress",
           "type":"address"
        }
     ],
     "name":"updateDrypAddress",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"newDrypPool",
           "type":"address"
        }
     ],
     "name":"updateDrypPoolAddress",
     "outputs":[
        {
           "internalType":"bool",
           "name":"",
           "type":"bool"
        }
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        
     ],
     "name":"withdrawAllFromNonRedeemBasket",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"_amount",
           "type":"uint256"
        }
     ],
     "name":"withdrawFromUnredeemableBaseket",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  },
  {
     "inputs":[
        {
           "internalType":"address",
           "name":"_asset",
           "type":"address"
        },
        {
           "internalType":"uint256",
           "name":"_amount",
           "type":"uint256"
        }
     ],
     "name":"withdrawFromredeemableBaseket",
     "outputs":[
        
     ],
     "stateMutability":"nonpayable",
     "type":"function"
  }
]